export const ACTIONS = {
  CATEGORIES: {
    DELETE_CAT: "DELETE_CAT",
    GET_CAT: "GET_CAT",
    EDIT_CAT: "EDIT_CAT",
    CREATE_CAT: "CREATE_CAT",
    SET_DATA: "SET_DATA",
  },
  PAGES: {
    CREATE_PAGE: "CREATE_PAGE",
    GET_PAGE: "GET_PAGE",
    EDIT_PAGE: "EDIT_PAGE",
    DELETE_PAGE: "DELETE_PAGE",
    CURRENT_PAGE: "CURRENT_PAGE",
  },
  POSTS: {
    CREATE_POST: "CREATE_POST",
    GET_POST: "GET_POST",
    EDIT_POST: "EDIT_POST",
    DELETE_POST: "DELETE_POST",
    CURRENT_POST: "CURRENT_POST",
  },
  COMMENTS: {
    SAVE_COMMENT: "SAVE_COMMENT",
    DELETE_COMMENT: "DELETE_COMMENT",
    GET_COMMENTS: "GET_COMMENTS",
    CURRENT_COMMENT: "CURRENT_COMMENT",
  },
  SUBSCRIBERS: {
    SUBSCRIBE: "SUBSCRIBE",
    DELETE_SUBSCRIBER: "DELETE_SUBSCRIBER",
    GET_SUBSCRIBERS: "GET_SUBSCRIBERS",
    CURRENT_SUBSCRIBER: "CURRENT_SUBSCRIBER",
  },
  MENU: {
    GET_MENU: "GET_MENU",
  },
  USER: {
    GET_USER: "GET_USER",
  },
  AUTHENTICATION: "AUTHENTICATION",
};
